# Generated by Django 4.0.4 on 2022-06-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_prices_fileupload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='describe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prices',
            name='day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prices',
            name='describe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
