# Generated by Django 4.0.4 on 2022-06-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_fileupload_describe_prices_day_prices_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
